version: '3'

services:

  mongo:
    image: mongo
    container_name: websys_mongo
    ports:
      - "27017:27017"

  mongo_admin:
    image: mongo-express
    container_name: websys_mongo_admin
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8081:8081"