# Extends jupyter/datascience-notebook
FROM jupyter/datascience-notebook

# Copies Jupyter notebooks used to format restaurant data
COPY AnalyzeThis.ipynb /home/jovyan/AnalyzeThis.ipynb

# Installs pymongo
RUN pip install pymongo